version: 2
formats: all
sphinx:
  configuration: flink-ai-flow/docs/conf.py
  fail_on_warning: false

build:
  image: latest
  apt_packages:
    - default-libmysqlclient-dev
    - build-essential

python:
  # For available versions, see:
  # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-image
  version: 3.7  # Keep in sync with .github/workflows/checks.yml
  install:
    - requirements: flink-ai-flow/docs/requirements.txt

    - method: pip
      path: flink-ai-flow/
    - method: pip
      path: flink-ai-flow/lib/notification_service
    - method: pip
      path: flink-ai-flow/lib/airflow
