census_batch_train:
  platform: local
  engine: flink
  job_name: census_batch_train
  flink_home: xxx # currently not used. Instead, 'flink' in system environment will be chose
  local_mode: cluster
  language_type: PYTHON

census_stream_train:
  platform: local
  engine: flink
  job_name: census_stream_train
  flink_home: xxx # currently not used. Instead, 'flink' in system environment will be chose
  local_mode: cluster
  language_type: PYTHON

census_stream_predict:
  platform: local
  engine: flink
  job_name: census_stream_predict
  flink_home: xxx # currently not used. Instead, 'flink' in system environment will be chose
  local_mode: cluster
  language_type: PYTHON
